// <auto-generated />
namespace messengerX_v._1._0._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BlockedUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlockedUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202403071304511_BlockedUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
